### ISSUE TITLE
Make Python 2 and 3 console formatting consistent

### ISSUE THREAD

**Issue by iRaffnix** [iminuit/iminuit#123]
Dear all!

unfortunately iminuit is not Python3 compatible.
Is it planned to overcome this little problem in the future?

Cheers,
iRaffnix

**Comment by mattngc** [comment]
Hi, has there been any movement on this issue? Python 3 support for iminuit would be fantastic.

**Comment by piti118** [comment]
Okie. I'll investigate this for real this time.

**Comment by piti118** [comment]
OK Done. Try it out. It "should" work. There might be a few kinks here and there please report those as well.

**Comment by kbarbary** [comment]
@piti118 Thanks so much. This is the last package I use that has been preventing me from switching to using Py3 full time. I'll report any problems I find.

**Comment by mattngc** [comment]
@piti118 Yes, thanks so much for this. I've being doing some preliminary testing today. So far I can't find any issues. But then I'm not an advanced user, just doing simple stuff so far. But no problems so far. Thanks again.

**Comment by mattngc** [comment]
This is working fine for me so far in python 3. Something I did notice however is that the console output is misaligned for values with exponents. To see this effect, copy code below into a text editor with fixed column widths. This might be a bug due to python 3 string handling being different to what you had before in python 2.

---------------------------------------------------------------------------------------------------------------------
|      |             Name             |  Value   | Para Err |   Err-   |   Err+   |  Limit-  |  Limit+  |          |
---------------------------------------------------------------------------------------------------------------------
|    0 |        Dalpha-cold_intensity =  6.913E+17 |  5.77E+13 |          |          |  5E+16   |  2E+18   |          |
|    1 |      Dalpha-cold_temperature =  41.29   |  0.003103 |          |          |  0       |  100     |          |
|    2 |       Dalpha-cold_wavelength =  655.9   |  3.965E-06 |          |          |  654     |  659     |          |
|    3 |   Dalpha-luke-warm_intensity =  2.608E+17 |  7.741E+13 |          |          |  0       |  6.071E+18 

Cheers, matt

**Comment by cdeil** [comment]
@mattngc – Yes, float formatting changed on Python 3. I think it would be best if we make all our output be the same on Py 2 / 3 by being explicit with the formatting everywhere. If someone here can help out with this and make a PR, please leave a comment. Otherwise I'll try to get it done tomorrow.

Changing the title of this PR now and leaving it open for this formatting issue now.

**Comment by mattngc** [comment]
Also, noticed that 'print_level=2' doesn't work in python 3. Levels 0 and 1 both work as expected, but not at level 2.

**Comment by piti118** [comment]
can you open another issue for print_level. I remember I forgot to fix it when I port it to MINUIT2.

**Comment by mattngc** [comment]
ok, done

**Comment by HDembinski** [comment]
Python 3 seems to work fine now, and the remaining issue with formatting is handled in a separate issue. I am closing this.
