### ISSUE TITLE
Add Windows build on Appveyor

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#161]
We should support Windows and add a build on Appveyor.
I'm putting this under the "long term" milestone because I don't know if `iminuit` actually works under Windows or how to best configure the build.

Examples:
https://github.com/astropy/astropy/blob/master/appveyor.yml
https://github.com/astropy/conda-builder-affiliated
https://github.com/ogrisel/python-appveyor-demo

@mwcraig – Do you have time to advise here, pointing to a good example for a non-astropy-affiliated package that has a good appveyor config? Or even try out `iminuit` on a Windows machine? I don't have access to one. (this is slightly Astropy-affiliated related ... iminuit is used for sncosmo and Gammapy and could be an interesting backend for astropy.modeling)

**Comment by mwcraig** [comment]
@cdeil - I would go with the appveyor.yml in astropy. The really critical part are the windows-related files in the folder `.continuous-integration`, which properly set up the microsoft compilers and SDKs for a particular  python+architecture combination.

Of course, I just read the "non-astropy-affiliated" part :). Maybe look at https://github.com/pelson/obvious-ci. In that one you would want `appveyor.yml` and whatever file the `CMD_IN_ENV` variable inside of it points to.

Looks like iminuit uses nose -- so is running the tests just a matter of grabbing the source and then `$ nose`? It has been a couple years since I used nose...

**Comment by cdeil** [comment]
Yes, runnig the tests is just these two commands:
```
$ python setup.py build_ext --inplace
$ nosetests -V
```

**Comment by cdeil** [comment]
But it needs a C++ compiler.

**Comment by mwcraig** [comment]
Tests passed (only tested on Win 7/64 bit/python 2).

Anaconda (or maybe conda build) installs mingw, which works in most cases. I've seen a few cases where mingw-compiled code fails but code compiled with MS visual c++ doesn't, and the latter is what the official python binaries are compiled with.

MSVC express is free, but configuring it and the necessary SDKs is a bit of pain.

**Comment by cdeil** [comment]
This was done today by @HDembinski - we now have an Appveyor build for iminuit: https://ci.appveyor.com/project/iminuit/iminuit
