### ISSUE TITLE
MIGRAD Execution - Iterations over all data or one data point?

### ISSUE THREAD

**Issue by jimcost** [iminuit/iminuit#186]
In a given MIGRAD call, for example

```python
>>> m.migrad(ncall = 10e4)
```
Does MIGRAD minimize the cost function over all data points given? Or does MIGRAD minimize the cost function one data point at a time?

I ask because the function I am looking to minimize, let's say 'Y(f)', contains a FFT call.  Thus, it looks like
```python
>>> y = np.sin(w*t + sigma)
>>> Y = np.rfft(y)
```
'Y' is the function I intend to fit.  As you might imagine, a FFT does not execute on a scalar.

Many thanks!

**Comment by cdeil** [comment]
@jimcost - MINUIT and MIGRAD don't know or want to know about your data points.

You as the user have to define your scalar cost function, and pass that function to MINUIT.
A colleague of mine did [this presentation](http://nbviewer.jupyter.org/github/astropy/astropy-model-ideas/blob/master/notebooks/sherpa_astropy_iminuit/sherpa_astropy_iminuit.ipynb#iminuit) a while ago to explain this, you might find the Figure there useful.

The cost function you give to MINUIT should take the parameters as input and return the total cost.
I.e. if you have a log likelihood or chi^2 per data point, you have to sum those all up and return the total in your cost function implementation.

Is it clear?

(I'm offline now, but will check back tomorrow morning.)

**Comment by jimcost** [comment]
Ahh yes, very clear.  Originally I had modeled my cost function off the code - 

`class MyChi2:

    def __init__(self, x, y):
        self.x, self.y = (x,y)

    def f(self, x, m, c):
        return m*x + c

    def __call__(self,m,c):
        return sum([(self.f(x,m,c)-y)**2 for x,y in zip(self.x ,self.y)])`

This is where the problem arose, because the 'zip' function iterates over the values.  I removed the zip and simply execute the summation over all data points - and voila the minimization executed.

I wonder though, why both this code I found [here](http://iminuit.readthedocs.io/en/latest/api.html#function-signature-extraction-ordering) and the chi-squared cost function in the probfit module iterates over the elements of the vector.

Many thanks.

**Comment by cdeil** [comment]
OK, closing this issue now.

> I wonder though, why both this code I found here and the chi-squared cost function in the probfit module iterates over the elements of the vector.

I don't know. In this example you could write `__call__` to use a Numpy array expression, instead of a Python list and calling sum. There might be other examples where the function `f` doesn't work for arrays of points `x` and you have to write `__call__` this way (or make a wrapper for `f` that loops over entries in `x`).

The nice thing about MINUIT is ... it doesn't care about your data or model, just your cost function callable. Well, it's nice, but it also means you have to always implement your own cost function. iminuit is not a modeling / fitting package like Sherpa in Python or RooFit in ROOT.

@piti118 wrote https://github.com/iminuit/probfit when he wrote iminuit ... that's a layer on top of iminuit that builds cost functions that's worth checking out. Personally I haven't used it much (except for playing around) ... your milage may vary.
