### ISSUE TITLE
using Minuit2 instead of SEAL minuit

### ISSUE THREAD

**Issue by giacomov** [iminuit/iminuit#193]
Similar to #124 

I am working on a project where the user can choose between Minuit2 from the ROOT package and iminuit for minimization problems.

In our experience, the former often outperform the latter in finding better solutions to minimization problems. The reason for the difference is that the algorithm in Minuit2 has changed slightly since SEAL minuit, and new fixes have been added to the code:

https://root.cern.ch/gitweb/?p=root.git;a=history;f=math/minuit2/src;h=60885f144b2a0682bd358c23e3f8ebd766847fea;hb=HEAD

Since Minuit2 is released also as a standalone package and is free open source software (http://project-mathlibs.web.cern.ch/project-mathlibs/sw/Minuit2/html/index.html), why sticking with SEAL minuit which is not maintained anymore?

**Comment by cdeil** [comment]
@giacomov - Thanks for bringing this up.

The top-level docs page indeed says that we're using SEAL Minuit:
http://iminuit.readthedocs.io/en/latest/#what-is-iminuit

But my understanding is that @piti118 in #145 updated to Minuit2 version 2.5 in July 2015, in response to #124.

Before we change the bundled version or docs page, I have some questions:

- So Minuit2 is now being maintained in the ROOT repo and [this](https://root.cern.ch/gitweb/?p=root.git;a=history;f=math/minuit2/src;h=60885f144b2a0682bd358c23e3f8ebd766847fea;hb=HEAD) is the changelog?
- What is the last stable version of standalone Minuit2 that was released?
- Are they still making stable versions or should we take versions of standalone Minuit2 or should we take versions from stable ROOT releases?

Does anyone know, or should we ask in the ROOT forum?

@piti118 - What is the procedure to update the bundled `Minuit2` for `iminuit`?
Is it just a `cp` command, or are there modifications we have to make? Can we document or script those, so that updating the bundled version becomes a simple and safe process that anyone can do?

**Comment by giacomov** [comment]
Hi,
thanks!

I opened a question in the ROOT forum:

https://root.cern.ch/phpBB3/viewtopic.php?f=15&t=22784

Let's see what they say. Hopefully they will answer to most of your questions.

**Comment by cdeil** [comment]
@giacomov - Thanks!

Please leave another comment here when you get some info.
(I can't remember my CERN passwd any more, so I can't easily watch the post.)

**Comment by henryiii** [comment]
I've made a copy of standalone Minuit 2 from the ROOT 6.08.04 source, with a CMake build system. It is at https://github.com/GooFit/Minuit2. The examples build, I haven't had a chance yet to test it in a larger system (GooFit).

**Comment by HDembinski** [comment]
This was fixed by PR #206, closing.
