### ISSUE TITLE
interface request: add np_vector, similar to np_matrix

### ISSUE THREAD

**Issue by HDembinski** [iminuit/iminuit#200]
```iminuit.Minuit``` already provides a nice convenience interface to get the full covariance matrix after the fit: ```iminuit.Minuit.np_matrix()```. Unfortunately, there is no equivalent method for getting the parameter vector. For consistency reasons and because I personally need this all the time, I would like to see a method ```iminuit.Minuit.np_vector()``` that returns a vector of the fitted parameters in the same order as `np_matrix` is returned.

**Comment by cdeil** [comment]
I see that `Minuit.np.matrix` is basically a one-liner calling `np.array` on `Minuit.matrix`:
https://github.com/iminuit/iminuit/blob/fc5cc5d89f15921fbd78b27396eda22a5f99b487/iminuit/_libiminuit.pyx#L649
```
np_matrix = np.array(minuit.matrix())
```

I looked around a bit, and it seems no equivalent of `Minuit.matrix` exists, that exposes an ordered parameter list. One currently has to use this to turn the `Minuit.values` dict into a list with the parameters in the right order?
```
[m.values[name] for name in m.list_of_vary_param()]
```
Or did I just miss that property and it exists already?

@HDembinski - So basically what you're proposing is a property that returns this, no?
```
np.array(m.values[name] for name in m.list_of_vary_param())
```

---

In principle I'm +1 to add such a convenience(s).

But given that anything we add should remain there forever, I would prefer us to be careful / conservative with additions and to have someone review and propose a full addition of more Python-based properties (using tuples / lists / dicts, or instead changing to OrderedDict to avoid duplicating properties just to get sorted lists), and then which properties we really want to re-expose using Numpy arrays instead of just letting the caller pass an existing list or tuple into `np.array`. Note that there's different variants like "all parameters" or only the "varying parameters" or ... it would also be reasonable to add 10 new Numpy array convenience properties.

The alternative to adding conveniences is to improve the docs. Probably some mix of those two options would be idea.

@HDembinski @piti118 @alexpearce or anyone - what do you propose we add? Anyone willing to send a pull request (maybe wait for a few days to get opinions here)?

**Comment by cdeil** [comment]
> For people who work with numpy a lot, it is simply more natural to get the fit result and the covariance matrix as numpy ndarrays. It scales better when you need to change the number of fitted parameters a lot, ...

Agreed that supporting interaction (getting and setting) with Numpy arrays should be a goal, i.e. to make that as convenient as possible. But Minuit first and foremost has a Python tuple / dict / list interface. Usually interacting with Numpy arrays instead of tuples is possible with one-liners. I'm +100 to document that better (the code snippets from this issue discussion should be added to docstrings or even a section "Numpy array interface of iminuit.Minuit" in the high-level docs.

But after looking a bit more closely at the current API http://iminuit.readthedocs.io/en/latest/api.html I'm not sure I agree with your suggestions, @HDembinski . In the end it's a matter of taste how much and how exactly to expose a numpy array interface, so hopefully others (e.g. @piti118 @alexpearce) will chime in as well.

I'm -1 on deprecating [Minuit.matrix](http://iminuit.readthedocs.io/en/latest/api.html#iminuit.Minuit.matrix). I'm using it in years old scripts and I think many others are too, so deprecating it is an inconvenience. I also think it's very nice to have access to the matrix in covariance or correlation form, as well as with fixed parameters in or out. All of those things are needed / useful, and the current a`matrix` and `np_matrix` are exactly how I would put it. I realise it partly duplicates other things (like `covariance`), which isn't nice, but note that this issue is proposing to add more duplication / convenience properties for info that is already exposed.

For me, the thing that sticks out as most confusing is http://iminuit.readthedocs.io/en/latest/api.html#iminuit.Minuit.args , I think improving the docstring there and saying how it compares to `.values` would be most valuable. See
https://github.com/iminuit/iminuit/blob/fc5cc5d89f15921fbd78b27396eda22a5f99b487/iminuit/_libiminuit.pyx#L379
Is it equivalent to `self.values[key] for key in self.parameters`? Then we could just write
```
def np_values(self):
    return np.array(self.args)
```
or really adding this has very little value, because the caller can just do `np.array(m.args)`.

Finally, it's not clear to me if we can't just change from dict -> OrderedDict everywhere, and have parameters in order, and then `np.array(m.values.values())` and `np.array(m.errors.values())` would work, and probably some similar expression for `merrors`?

So bottom line: I would prefer if we first add a short section or page "Numpy array interface of iminuit.Minuit" to the docs with examples how to do all the things you want to do, and how they can be done currently. I think providing that would be a huge benefit to many users. Adding one-line convenience methods and properties can be done as well, but that would probably always remain incomplete (e.g. what about "merrors"? where can I pass numpy arrays to Minuit methods or assign numpy arrays to properties? I don't know the answer to that question).

Finally, just to be clear: we're only talking about adding Numpy array support in the interface that goes through the Python tuple interface? I.e. there are absolutely no performance improvements in any of those additions, right? Those would require changing `iminuit.Minuit` to internally store things as Numpy arrays, which would be a huge change, and in the end unlikely to matter for performance, at least as long as you don't have e.g. 10,000 or 100,000 parameters, i.e. a regime where as I understand Minuit isn't the optimiser of choice anyways.

**Comment by HDembinski** [comment]
@cdeil and I discussed this a bit offline. My argument is that most people nowadays use numpy, so it would be nice to have a convenient interface with clear names for those users. Even if you could get the same via one-liners, an one-liner that I have to type *in every single script* is still annoying.

`Minuit.args` and `Minuit.matrix()` are not good names. Imagine you read a script where these appear, it is not clear what these do from the name alone. "Readability counts" (Zen of Python). We owe it to the numpy users that we do not thread them as second-class citizens. My suggestion is to mimic the normal interface `Minuit.values` and `Minuit.covariance` and make equivalent numpy versions `Minuit.np_values()` and `Minuit.np_covariance()`. This leads to much more readable code, and there is a clear correspondence between the non-numpy and numpy interfaces.

We already discussed the option of changing everything to OrderedDict, it is a good idea, but it would not work for the covariance matrix.

I am ok with not deprecating `matrix()`, I may have been overzealous here.

I am fine with adding Numpy array support that goes through the Python tuple interface, as performance is not a concern. However, I would like to have the interface in such a way that it is possible to optimize this in the future, if someone wants to put in the effort.

**Comment by HDembinski** [comment]
PR was merged with master, closing this :)
